-- California Contractor Search initial schema
-- Source values are preserved; normalized values live in separate columns.

create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

create or replace function public.normalize_search_text(input text)
returns text
language sql
immutable
parallel safe
set search_path = pg_catalog
as $$
  select trim(regexp_replace(regexp_replace(lower(coalesce(input, '')), '([a-z])\s*-\s*([0-9])', '\1\2', 'g'), '[^a-z0-9]+', ' ', 'g'));
$$;

create or replace function public.normalize_business_name(input text)
returns text
language sql
immutable
parallel safe
set search_path = pg_catalog
as $$
  select trim(regexp_replace(regexp_replace(public.normalize_search_text(input), '^the\s+', ''), '\s+(llc|inc|incorporated|corp|corporation|company|co)$', ''));
$$;

create table public.licenses (
  id bigint generated by default as identity primary key,
  license_number text not null unique,
  business_name text not null,
  business_name_normalized text not null default '',
  license_status text not null check (license_status in ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'INACTIVE')),
  license_type text,
  issue_date date,
  expiration_date date,
  address_line_1 text,
  address_line_2 text,
  city text,
  state text not null default 'CA',
  zip text,
  phone text,
  entity_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source_updated_at timestamptz
);

create table public.classifications (
  id bigint generated by default as identity primary key,
  code text not null unique check (code = lower(regexp_replace(code, '[^a-zA-Z0-9]', '', 'g'))),
  name text not null,
  slug text not null unique,
  description text,
  aliases text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.license_classifications (
  id bigint generated by default as identity primary key,
  license_id bigint not null references public.licenses(id) on delete cascade,
  classification_id bigint not null references public.classifications(id) on delete cascade,
  unique (license_id, classification_id)
);

create table public.personnel (
  id bigint generated by default as identity primary key,
  license_id bigint not null references public.licenses(id) on delete cascade,
  first_name text not null,
  middle_name text,
  last_name text not null,
  full_name text not null,
  full_name_normalized text not null default '',
  role text,
  association_date date,
  disassociation_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.bonds (
  id bigint generated by default as identity primary key,
  license_id bigint not null references public.licenses(id) on delete cascade,
  bond_type text not null,
  bond_company text,
  bond_number text,
  bond_amount numeric(12, 2),
  effective_date date,
  cancellation_date date,
  unique (license_id, bond_type, bond_number)
);

create table public.workers_comp (
  id bigint generated by default as identity primary key,
  license_id bigint not null references public.licenses(id) on delete cascade,
  carrier text,
  policy_number text,
  effective_date date,
  expiration_date date,
  exemption boolean not null default false,
  unique (license_id, policy_number)
);

create or replace function public.set_normalized_fields()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if tg_table_name = 'licenses' then
    new.business_name_normalized := public.normalize_business_name(new.business_name);
  elsif tg_table_name = 'personnel' then
    new.full_name_normalized := public.normalize_search_text(new.full_name);
  end if;
  return new;
end;
$$;

create trigger licenses_normalize_before_write before insert or update of business_name on public.licenses
for each row execute function public.set_normalized_fields();
create trigger personnel_normalize_before_write before insert or update of full_name on public.personnel
for each row execute function public.set_normalized_fields();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin new.updated_at := now(); return new; end;
$$;

create trigger licenses_set_updated_at before update on public.licenses for each row execute function public.set_updated_at();
create trigger classifications_set_updated_at before update on public.classifications for each row execute function public.set_updated_at();
create trigger personnel_set_updated_at before update on public.personnel for each row execute function public.set_updated_at();

create index licenses_business_name_trgm_idx on public.licenses using gin (business_name_normalized extensions.gin_trgm_ops);
create index licenses_city_lower_idx on public.licenses (lower(city));
create index licenses_zip_idx on public.licenses (zip);
create index licenses_status_idx on public.licenses (license_status);
create index personnel_full_name_trgm_idx on public.personnel using gin (full_name_normalized extensions.gin_trgm_ops);
create index personnel_license_id_idx on public.personnel (license_id);
create index license_classifications_license_idx on public.license_classifications (license_id);
create index license_classifications_classification_idx on public.license_classifications (classification_id);
create index bonds_license_id_idx on public.bonds (license_id);
create index workers_comp_license_id_idx on public.workers_comp (license_id);

-- Centralized database ranking primitive for the production search adapter.
create or replace function public.search_license_ids(search_query text, result_limit integer default 50)
returns table (license_id bigint, relevance_score double precision)
language sql
stable
set search_path = pg_catalog
as $$
  with query as (
    select
      public.normalize_search_text(search_query) as normalized,
      regexp_replace(public.normalize_search_text(search_query), '\s', '', 'g') as compact,
      public.normalize_business_name(search_query) as business
  )
  select
    l.id,
    (
      case when l.license_number = q.compact then 1000 else 0 end +
      case when l.business_name_normalized = q.business then 800
           when l.business_name_normalized like q.business || '%' then 650 else 0 end +
      coalesce(extensions.similarity(l.business_name_normalized, q.business) * 400, 0) +
      case when lower(l.city) = q.normalized then 450 else 0 end +
      case when l.zip = q.compact then 500 else 0 end +
      case when exists (select 1 from public.personnel p where p.license_id = l.id and p.full_name_normalized = q.normalized) then 600 else 0 end +
      case when exists (
        select 1 from public.personnel p
        where p.license_id = l.id and extensions.similarity(p.full_name_normalized, q.normalized) >= 0.35
      ) then 300 else 0 end +
      case when exists (
        select 1 from public.license_classifications lc
        join public.classifications c on c.id = lc.classification_id
        where lc.license_id = l.id
          and (c.code = q.compact or public.normalize_search_text(c.name || ' ' || array_to_string(c.aliases, ' ')) like '%' || q.normalized || '%')
      ) then 550 else 0 end +
      case when l.license_status = 'ACTIVE' then 10 else 0 end
    )::double precision as relevance_score
  from public.licenses l cross join query q
  where q.normalized <> '' and (
    l.license_number = q.compact
    or l.business_name_normalized like '%' || q.business || '%'
    or extensions.similarity(l.business_name_normalized, q.business) >= 0.25
    or lower(l.city) like '%' || q.normalized || '%'
    or l.zip = q.compact
    or exists (select 1 from public.personnel p where p.license_id = l.id and (p.full_name_normalized like '%' || q.normalized || '%' or extensions.similarity(p.full_name_normalized, q.normalized) >= 0.35))
    or exists (
      select 1 from public.license_classifications lc join public.classifications c on c.id = lc.classification_id
      where lc.license_id = l.id and (c.code = q.compact or public.normalize_search_text(c.name || ' ' || array_to_string(c.aliases, ' ')) like '%' || q.normalized || '%')
    )
  )
  order by relevance_score desc, l.business_name asc
  limit least(greatest(result_limit, 1), 100);
$$;

alter table public.licenses enable row level security;
alter table public.classifications enable row level security;
alter table public.license_classifications enable row level security;
alter table public.personnel enable row level security;
alter table public.bonds enable row level security;
alter table public.workers_comp enable row level security;

create policy "Public read licenses" on public.licenses for select to anon, authenticated using (true);
create policy "Public read classifications" on public.classifications for select to anon, authenticated using (true);
create policy "Public read license classifications" on public.license_classifications for select to anon, authenticated using (true);
create policy "Public read personnel" on public.personnel for select to anon, authenticated using (true);
create policy "Public read bonds" on public.bonds for select to anon, authenticated using (true);
create policy "Public read workers comp" on public.workers_comp for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on table
  public.licenses,
  public.classifications,
  public.license_classifications,
  public.personnel,
  public.bonds,
  public.workers_comp
to anon, authenticated;

revoke execute on function public.normalize_search_text(text) from public;
revoke execute on function public.normalize_business_name(text) from public;
revoke execute on function public.set_normalized_fields() from public;
revoke execute on function public.set_updated_at() from public;
revoke execute on function public.search_license_ids(text, integer) from public;

grant execute on function public.normalize_search_text(text) to anon, authenticated;
grant execute on function public.normalize_business_name(text) to anon, authenticated;
grant execute on function public.search_license_ids(text, integer) to anon, authenticated;
